In [4]:
import numpy as np


In [2]:
import numpy as np
a=[1,2,3,4,5,6]
mya=np.array(a)
mya


array([1, 2, 3, 4, 5, 6])

In [5]:
#second method
myar=np.array([1,2,3,4,5,6])
myar

array([1, 2, 3, 4, 5, 6])

In [6]:
a=[1,3,5,7,8]
myar=np.array(a)
myar

array([1, 3, 5, 7, 8])

In [8]:
#second method
myarray=np.array([1,3,5,7,9])
myarray

array([1, 3, 5, 7, 9])

In [14]:
import numpy as np
b=[3,6,9,12,15]
mmyarr=np.array(b)
mmyarr

array([ 3,  6,  9, 12, 15])

In [15]:
#second method
mmyarr=np.array([3,6,9,12,15])
mmyarr

array([ 3,  6,  9, 12, 15])

In [17]:
c=[1,2,3,4,5,6,7,8,9]
mmya=np.array(c)
mmya

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
#second method
mmya=np.array([1,2,3,4,5,6,7,8,9,10])
mmya

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
import numpy as np
a=[]
n=int(input("enre the size of array:"))
for i in range(n):
    val=int(input("entre the value:"))
    a.append(val)
myaar=np.array(a)
myaar

enre the size of array:5
entre the value:1
entre the value:2
entre the value:3
entre the value:4
entre the value:5


array([1, 2, 3, 4, 5])

In [4]:
a=[]
n=int(input("entre the size of array:"))
for i in range(n):
    val=int(input("entre the value:"))
    a.append(val)
myaa=np.array(a)
myaa


entre the size of array:6
entre the value:1
entre the value:22
entre the value:33
entre the value:44
entre the value:55
entre the value:66


array([ 1, 22, 33, 44, 55, 66])

In [7]:
a=[]
x=int(input("entre the size of array:"))
for i in range(x):
    val=int(input("entre the value:"))
    a.append(val)
myaar=np.array(a)
myaar

entre the size of array:5
entre the value:11
entre the value:22
entre the value:33
entre the value:44
entre the value:55


array([11, 22, 33, 44, 55])

In [8]:
a=[]
n=int(input("entre the number the size of array:"))
for i in range(n):
    val=int(input("entre the value:"))
    a.append(val)
myaar=np.array(a)
myaar

entre the number the size of array:6
entre the value:111
entre the value:222
entre the value:333
entre the value:444
entre the value:555
entre the value:666


array([111, 222, 333, 444, 555, 666])

In [14]:
#creating numpy(2 dimiension)
import numpy as np
d=[[1,2,3],[1,2,3],[1,2,3]]
myarr=np.array(d)
myarr

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [2]:
#second method
import numpy as np
myaar=np.array([[1,2,3,4],[3,4,5,6],[2,3,4,5]])
myaar

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [2, 3, 4, 5]])

In [3]:
a=[[1,2,3,4],[1,2,4,5],[1,2,3,4]]
myaar=np.array(a)
myaar

array([[1, 2, 3, 4],
       [1, 2, 4, 5],
       [1, 2, 3, 4]])

In [5]:
# second method
myaar=np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
myaar

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [8]:
print("total dimensions=",myaar.ndim)
print("total size(row,coloum)=",myaar.shape)

total dimensions= 2
total size(row,coloum)= (3, 4)


In [10]:
c=[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]
myya=np.array(c)
myya

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [11]:
myaar=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
myaar

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [12]:
print("total dimesion=",myaar.ndim)
print("total size(row,coloum)=",myaar.shape)

total dimesion= 2
total size(row,coloum)= (3, 5)


In [13]:
myaar

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [14]:
print("total dimension=",myaar.ndim)
print("total size(row,coloum)=",myaar.shape)

total dimension= 2
total size(row,coloum)= (3, 5)


In [16]:
t=[[1,2,3,4,5,6],[2,3,4,5,6,7],[1,2,3,4,5,6]]
myaar=np.array(t)
myaar

array([[1, 2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6]])

In [17]:
myaar=np.array([[1,2,3,4,5,6],[3,4,5,6,7,8],[4,5,6,7,8,9]])
myaar
print("total dimension=",myaar.ndim)
print("total size=",myaar.shape)

total dimension= 2
total size= (3, 6)


In [2]:
#np.zeros() function
import numpy as np
arr= np.zeros(5)
arr


array([0., 0., 0., 0., 0.])

In [3]:
arr=np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
arr=np.zeros((2,3,4))
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [6]:
arr=np.zeros(2)
arr

array([0., 0.])

In [17]:
arr=np.zeros((2,3,4))
arr


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [18]:
arr=np.zeros((2,3,4,5))
arr

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [9]:
arr=np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
#np.ones() functio0n
srr=np.ones(5)
srr

array([1., 1., 1., 1., 1.])

In [12]:
arr=np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
arr=np.ones((2,3,4))
arr

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [14]:
#np.eye() function
arr=np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
arr=np.eye(2,3)
arr

array([[1., 0., 0.],
       [0., 1., 0.]])

In [21]:
arr=np.eye(2,3)
arr

array([[1., 0., 0.],
       [0., 1., 0.]])

In [22]:
# np.diag()function
arr=np.diag([2])
arr

array([[2]])

In [23]:
arr=np.diag([2,3])
arr

array([[2, 0],
       [0, 3]])

In [25]:
arr=np.diag([2,3,4])
arr

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [26]:
arr=np.diag([2,3,4,5])
arr

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [27]:
arr=np.diag([2,3,4,5,6])
arr

array([[2, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 6]])

In [29]:
# serach diag function
arr=np.diag([2,3,4,5,6])
np.diag(arr)


array([2, 3, 4, 5, 6])

In [30]:
arr=np.diag([2,3,4,5])
np.diag(arr)

array([2, 3, 4, 5])

In [31]:
arr=np.diag([2,3,4])
np.diag(arr)


array([2, 3, 4])

In [46]:
# np.random.randint() fuction
arr=np.random.randint(1,10,3)
arr

array([3, 8, 7])

In [62]:
arr=np.random.randint(1,20,4)
arr

array([16, 17,  5, 11])

In [73]:
arr=np.random.randint(1,100,5)
arr


array([34, 15, 71, 45, 32])

In [86]:
arr=np.random.randint(1,10,3)
arr

array([2, 4, 2])

In [93]:
arr=np.random.randint(1,200,3)
arr

array([102,  90, 112])

In [94]:
# np.random.rand() function
arr=np.random.rand(5)
arr

array([0.21530683, 0.0499119 , 0.81778979, 0.39768589, 0.67731794])

In [95]:
arr=np.random.rand(1)
arr

array([0.76924863])

In [96]:
arr=np.random.rand(2)
arr

array([0.37825187, 0.48965112])

In [98]:
arr=np.random.rand(3)
arr

array([0.71711277, 0.36543753, 0.20895175])

In [99]:
arr=np.random.rand(3)
arr

array([0.64105349, 0.35802651, 0.37563514])

In [100]:
arr=np.random.rand(4)
arr

array([0.56651904, 0.97268165, 0.48397482, 0.60213093])

In [101]:
arr=np.random.rand(2,3)
arr

array([[0.24146737, 0.40812946, 0.12107611],
       [0.44785698, 0.87371192, 0.85220133]])

In [102]:
arr=np.random.rand(3,3)
arr

array([[0.17784365, 0.15081239, 0.55576277],
       [0.66771943, 0.36576623, 0.48071868],
       [0.58576917, 0.34166534, 0.86390852]])

In [103]:
arr=np.random.rand(2,3,4)
arr

array([[[0.95673969, 0.73100859, 0.34710121, 0.33671841],
        [0.24367283, 0.01174093, 0.01470177, 0.30404593],
        [0.13050558, 0.82830487, 0.9140606 , 0.57218193]],

       [[0.99704522, 0.55969994, 0.63442917, 0.27365717],
        [0.6492664 , 0.29084954, 0.88668253, 0.93158406],
        [0.46898951, 0.49889329, 0.05596526, 0.15196019]]])

In [104]:
arr=np.random.rand(2,3,4,5)
arr

array([[[[0.4601971 , 0.24790901, 0.86591722, 0.13632984, 0.48793406],
         [0.41178393, 0.13852284, 0.67712703, 0.16526136, 0.31531953],
         [0.14286408, 0.9973655 , 0.63636693, 0.21339057, 0.21627   ],
         [0.86477026, 0.16192896, 0.09832471, 0.81261239, 0.791088  ]],

        [[0.63239775, 0.05591995, 0.46027618, 0.42530311, 0.49352903],
         [0.73187742, 0.01798488, 0.40167323, 0.50414963, 0.32187739],
         [0.1910946 , 0.78289429, 0.84242333, 0.40778031, 0.21367322],
         [0.53741508, 0.8311511 , 0.32928022, 0.71367516, 0.28679119]],

        [[0.82470547, 0.30188793, 0.67477077, 0.46173307, 0.17962937],
         [0.00530446, 0.24156456, 0.16253459, 0.88430303, 0.65004727],
         [0.73988585, 0.10271245, 0.67705822, 0.05210445, 0.26164516],
         [0.60309562, 0.63805233, 0.80485344, 0.44742337, 0.96746442]]],


       [[[0.61913085, 0.19179826, 0.17950973, 0.51224419, 0.6622814 ],
         [0.15157156, 0.88224636, 0.17108459, 0.45728987, 0.84411973]

In [105]:
# np.random.randn() function
arr=np.random.randn(5)
arr

array([-0.27566017,  0.66869324,  0.74717376, -1.96610312,  0.17735072])

In [106]:
arr=np.random.randn(2,3)
arr

array([[-1.17895651, -0.07417857,  0.35253407],
       [-0.4738399 ,  0.76903781,  1.5319494 ]])

In [107]:
arr=np.random.randn(2,3,4)
arr

array([[[-1.08780576,  0.04544624,  1.28648777,  0.3562246 ],
        [ 0.98025666,  1.51052538, -1.12370755, -2.01186491],
        [-0.50078759, -0.20806393, -0.89350454,  0.05090007]],

       [[ 2.77683528, -1.3292314 ,  0.36635138,  1.82984644],
        [ 0.14346609,  1.27850549, -0.82297814,  1.52699327],
        [ 1.39290264, -1.59385533, -0.19289421,  0.84717039]]])

In [108]:
arr=np.random.randn(2,3,4,5)
arr

array([[[[ 1.66415823e+00,  9.16436396e-01, -1.54693280e+00,
          -9.71106454e-01,  1.36456697e+00],
         [-4.69481370e-01,  2.37437791e-01, -1.14882747e+00,
           7.97137717e-01, -3.01603693e-01],
         [ 6.58071726e-01, -1.71650330e+00, -7.76534268e-01,
           2.98198797e-01,  5.24137834e-01],
         [-9.69616278e-02, -4.88820822e-01,  3.41274065e-02,
           1.86948394e+00, -9.88512448e-01]],

        [[ 4.53327914e-01,  6.69841488e-01, -5.47269896e-04,
           8.34166279e-01, -7.96438170e-01],
         [ 3.56332947e-01,  1.87526563e+00,  1.34519147e+00,
          -2.68940283e-01,  4.16190639e-02],
         [-4.44662894e-01, -8.64075750e-01,  6.70542214e-01,
          -7.02467548e-01,  1.58983089e+00],
         [-1.20152432e+00, -7.96092904e-01, -9.32378528e-01,
           1.42581337e-01,  3.06394672e-01]],

        [[ 1.98303145e-01,  1.41255544e+00, -3.47235514e-01,
           1.22090334e+00, -9.77068400e-01],
         [-1.27172032e+00,  8.01411798e-01

In [2]:
import numpy as np
a=[]
size=int(input("enttre the size of number?"))
for i in range(size):
    val=int(input("entre the value"))
    a.append(val)
arr=np.array(a)
for i in range(arr.size):
    print(arr[i])
    arr.size
    

enttre the size of number?4
entre the value1
entre the value2
entre the value3
entre the value4
1
2
3
4


In [4]:
import numpy as np
a=[]
size=int(input("entre the number of size:"))
for i in range(size):
    val=int(input("entre the value:")
            a.append(val)
arr=np.array(a)
for i in range (arr.size):
            print(arr[i])
            arr.size
            
            
            
    
            
            

SyntaxError: invalid syntax (3675447961.py, line 6)

In [6]:
import numpy as np
arr=np.random.randint(1,100,12)
print("total dimesion=",arr.ndim)
arr=arr.reshape(6,2)
print("total dimesion=",arr.ndim)
arr=arr.reshape(3,2,2)
print("total dimesion=",arr.ndim)
arr

total dimesion= 1
total dimesion= 2
total dimesion= 3


array([[[49, 34],
        [49, 74]],

       [[ 3, 23],
        [ 6, 20]],

       [[13, 89],
        [29, 42]]])

In [4]:
print("total no=",arr.ndim)

total no= 1


In [9]:
import numpy as np
arr=np.random.randint(1,10,6)
print("after dimension=",arr.ndim)
arr= arr.reshape(3,2)
print("after dimension=",arr.ndim)
arr=arr.reshape(1,3,2)
print("after dimension=",arr.ndim)
arr=arr.reshape (6)
print("after dimension=",arr.ndim)
arr=arr.reshape(3,2,1)
arr

after dimension= 1
after dimension= 2
after dimension= 3
after dimension= 1


array([[[5],
        [4]],

       [[2],
        [4]],

       [[5],
        [7]]])

In [11]:
import numpy as np
arr=np.random.randint(1,20,10)
arr


array([10, 15,  2,  3,  9,  4,  1,  9,  5,  8])

In [13]:
print("after dimesion=",arr.ndim)
print("after shape=",arr.shape)


after dimesion= 1
after shape= (10,)


In [18]:
arr=arr.reshape(5,2)
print("after dimesional=",arr.ndim)
print("after shape=",arr.size)

after dimesional= 2
after shape= 10


In [20]:
arr=arr.reshape(5,2,1)
print("after dimesinal=",arr.ndim)
print("after size=",arr.size)
arr

after dimesinal= 3
after size= 10


array([[[10],
        [15]],

       [[ 2],
        [ 3]],

       [[ 9],
        [ 4]],

       [[ 1],
        [ 9]],

       [[ 5],
        [ 8]]])

In [21]:
arr=arr.reshape(10)
print("after dimesional=",arr.ndim)
print("after size=",arr.size)
arr

after dimesional= 1
after size= 10


array([10, 15,  2,  3,  9,  4,  1,  9,  5,  8])

In [1]:
import numpy as np
are=np.random.randint(1,20,10)

In [38]:
import numpy as np
np.random.seed(1)
arr=np.random.randint(1,100,12)
arr.size
arr




array([38, 13, 73, 10, 76,  6, 80, 65, 17,  2, 77, 72])

In [ ]:
import numpy as np
np.random.seed(13)
arr=np.random.randint(1,100,15)
arr.size
arr

In [37]:
arr.size

15

In [38]:
import numpy as np
a=[]
size= int(input("entre the many number:")
for i in range(size):
    val=int(input("entre the value:")
    a.append (val)
arr= np.array(a)
for i in range(arr.size):
            print(arr[i])
            
sum=0
for i in range(arr.size):
            sum+=arr[i]
print("sum of element=",sum)
print(arr)

SyntaxError: invalid syntax (2617597295.py, line 4)

In [6]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,100])
slicing = a[3:7]
slicing [:]=0
a

array([ 10,  20,  30,   0,   0,   0,   0,  80,  90, 100])

In [9]:
a= np.array([10,20,30,40,50,60,70,80,90,100])
slicing = a[3:6] . copy()
slicing [:]=0
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [12]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
slicing = a[2:6]
slicing [:]= 0
a

array([ 1,  2,  0,  0,  0,  0,  7,  8,  9, 10])

In [13]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
slicing = a[2:6]. copy()
slicing [:] = 0
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
a= np.arange(1,11)
a
a>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [19]:
a=np.arange(1,21)
a
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [24]:
arr=np.arange(1,16)
arr
b=arr>10
arr[b]

array([11, 12, 13, 14, 15])

In [25]:
arr=np.arange(1,31)
arr
b= arr<15
arr[b]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
arr = np.arange (1,31)
arr
arr[arr%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [27]:
arr = np. arange (1,21)
arr
arr[arr%2 != 0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [28]:
arr[arr==10]

array([10])

In [32]:
arr = np.arange(1,51)
arr
arr<20

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [34]:
arr = np.arange(1,51)
arr
b=arr<20
arr[b]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [35]:
arr= np.arange (1,51)
arr
arr[arr%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [36]:
arr=np.arange(1,51)
arr
arr[arr%2 != 0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [1]:
import numpy as np
arr = np. arange(1,6)
arr*2

array([ 2,  4,  6,  8, 10])

In [2]:
arr= np.arange (1,11)
arr*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [3]:
arr=np.arange(1,26)
b=arr*2
print("multiply=",b)

multiply= [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


In [4]:
arr=np.arange(1,26)
b=arr**2
print("moduls of arr=",b)

moduls of arr= [  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289 324
 361 400 441 484 529 576 625]


In [5]:
arr=np.arange(1,10)
b=arr**2
b

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [7]:
arr=np.arange(1,6)
arr**2


array([ 1,  4,  9, 16, 25], dtype=int32)

In [8]:
arr=np.arange(1,6)
a=arr+2
print("addition=",a)

addition= [3 4 5 6 7]


In [9]:
arr =np.arange(1,11)
arr+3


array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [10]:
arr1=np.arange(1,6)
arr2=np.arange(11,16)
arr3=arr1+arr2
print("addition=",arr3)

addition= [12 14 16 18 20]


In [3]:
import numpy as np
arr=np.arange(1,10)
arr1=np.arange(11,20)
arr2=arr+arr1
print("addition=",arr2)


addition= [12 14 16 18 20 22 24 26 28]


In [4]:
arr=np.arange(1,10)
arr1=np.arange(11,20)
arr2=arr-arr1
arr2

array([-10, -10, -10, -10, -10, -10, -10, -10, -10])

In [7]:
arr=np.arange(1,9)
arr2=np.arange(11,19)
arr=arr-arr2
arr

array([-10, -10, -10, -10, -10, -10, -10, -10])

In [8]:
arr=np.arange(1,10)
arr2=np.arange(11,20)
arr3=arr-arr2
print("substrction=",arr3)

substrction= [-10 -10 -10 -10 -10 -10 -10 -10 -10]


In [21]:
import numpy as np
a=np.array ([1,2,3,4]).reshape(2,2)
b=np.array ([5,6,7,8]).reshape(2,2)
c=a+b
print("array addition=",c)


array addition= [[ 6  8]
 [10 12]]


In [22]:
arr=np.array([11,12,14,15]).reshape(2,2)
arr1=np.array([21,22,23,24]).reshape(2,2)
c=a+b
print("array addtion=",c)

array addtion= [[ 6  8]
 [10 12]]


In [31]:
arr1=np.array([1,2,3,4]).reshape(2,2)
arr2=np.array([6,7,8,9]).reshape(2,2)
c=arr1/arr2
print("array divide=",c)


array divide= [[0.16666667 0.28571429]
 [0.375      0.44444444]]


In [32]:
arr1=np.array([1,2,3,4]).reshape(2,2)
arr2=np.array([6,7,8,9]).reshape(2,2)
a.dot(b)

array([[19, 22],
       [43, 50]])

In [36]:
arr1= np.array([1,2,3,4]).reshape(2,2)
arr2=np.array([7,8,9,10]).reshape(2,2)
c=arr1 * arr2 
print("multiply=",c)

multiply= [[ 7 16]
 [27 40]]


In [40]:
arr1= np.array([6,7,8,9]).reshape(2,2)
arr2=np.array([10,11,12,13]).reshape(2,2)
c=arr1 * arr2
print("array multiply=",c)

array multiply= [[ 60  77]
 [ 96 117]]


In [3]:
import numpy as np
arr= np.array ([10,20,30,40,50,60,70,80,90,100])
a=np.max(arr)
print("maxime number of array=",a)
b=np.min(arr)
print("miniume number of array=",b)
c=np.argmax(arr)
print("maxime no of  indexing=",c)
d=np.argmin(arr)
print("minium no of indexing=",d)
e=np.sqrt(arr)
print("sequre root of every number=",e)
f=np.sin(arr)
print("sin value of every number=",f)
g=np.cos(arr)
print("cos value of ever number=",g)


maxime number of array= 100
miniume number of array= 10
maxime no of  indexing= 9
minium no of indexing= 0
sequre root of every number= [ 3.16227766  4.47213595  5.47722558  6.32455532  7.07106781  7.74596669
  8.36660027  8.94427191  9.48683298 10.        ]
sin value of every number= [-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485 -0.30481062
  0.77389068 -0.99388865  0.89399666 -0.50636564]
cos value of ever number= [-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603 -0.95241298
  0.6333192  -0.11038724 -0.44807362  0.86231887]


In [6]:
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,])
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [7]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [8]:
b=np.linspace(1,20,12)
print("after number=",b)

after number= [ 1.          2.72727273  4.45454545  6.18181818  7.90909091  9.63636364
 11.36363636 13.09090909 14.81818182 16.54545455 18.27272727 20.        ]


In [10]:
c=np.linspace(1,30,5)
print("after numbert=",c)

after numbert= [ 1.    8.25 15.5  22.75 30.  ]


In [11]:
d=np.linspace(1,100,11)
print("after number=",d)

after number= [  1.   10.9  20.8  30.7  40.6  50.5  60.4  70.3  80.2  90.1 100. ]


In [12]:
e=np.linspace(1,200,10)
print("after numbr=",e)

after numbr= [  1.          23.11111111  45.22222222  67.33333333  89.44444444
 111.55555556 133.66666667 155.77777778 177.88888889 200.        ]


In [1]:
import numpy as np
np.random.seed(34)
matrix=np.random.randint(1,30,9).reshape(3,3)
matrix

array([[ 2, 27, 11],
       [10, 23, 22],
       [ 5,  4,  6]])

In [2]:
np.min(matrix)

2

In [3]:
np.max(matrix)

27

In [4]:
np.sum(matrix)

110

In [5]:
np.sum(matrix,axis=1)

array([40, 55, 15])

In [6]:
np.min(matrix,axis=1)

array([ 2, 10,  4])

In [7]:
np.max(matrix,axis=1)

array([27, 23,  6])

In [8]:
np.sum(matrix,axis=0)

array([17, 54, 39])

In [9]:
np.min(matrix,axis=0)

array([2, 4, 6])

In [10]:
np.max(matrix,axis=0)

array([10, 27, 22])

In [13]:
np.cumsum(matrix,axis=1)

array([[ 2, 29, 40],
       [10, 33, 55],
       [ 5,  9, 15]], dtype=int32)

In [14]:
np.cumsum(matrix,axis=0)

array([[ 2, 27, 11],
       [12, 50, 33],
       [17, 54, 39]], dtype=int32)

In [6]:
import numpy as np
np.random.seed(11)
matrix=np.random.randint(1,30,9).reshape(3,3)
a=np.sum(matrix)
print("matrix of sum=",a)
b=np.min(matrix)
print("matrix min number=",b)
c=np.max(matrix)
print("matrix max number=",c)
matrix
d=np.sum(matrix,axis=1)
e=np.min(matrix,axis=1)
f=np.max(matrix,axis=1)
g=np.sum(matrix,axis=0)
h=np.min(matrix,axis=0)
i=np.max(matrix,axis=0)

matrix of sum= 150
matrix min number= 2
matrix max number= 28


In [10]:
import numpy as np
np.random.seed(11)
matrix=np.random.randint(1,50,9).reshape(3,3)
matrix

array([[26, 17, 28],
       [18, 14, 13],
       [34,  8, 19]])

In [11]:
np.sum(matrix,axis=0)

array([78, 39, 60])

In [13]:
np.sum(matrix,axis=1)

array([71, 45, 61])

In [14]:
np.min(matrix,axis=1)

array([17, 13,  8])

In [15]:
np.min(matrix,axis=0)

array([18,  8, 13])

In [16]:
np.max(matrix,axis=1)

array([28, 18, 34])

In [17]:
np.max(matrix,axis=0)

array([34, 17, 28])

In [21]:
np.cumsum(matrix)

array([ 26,  43,  71,  89, 103, 116, 150, 158, 177], dtype=int32)

In [22]:
matrix


array([[26, 17, 28],
       [18, 14, 13],
       [34,  8, 19]])

In [23]:
np.cumsum(matrix,axis=1)

array([[26, 43, 71],
       [18, 32, 45],
       [34, 42, 61]], dtype=int32)

In [24]:
np.cumsum(matrix,axis=0)

array([[26, 17, 28],
       [44, 31, 41],
       [78, 39, 60]], dtype=int32)

In [1]:
import numpy as np
arr=np.random.randint(1,21,9)
arr


array([16, 20, 15, 10,  8, 11, 20,  3,  4])

In [2]:
arr=np.random.randint(1,21,9).reshape(3,3)
arr

array([[ 1, 10,  9],
       [ 5, 14, 17],
       [18,  3,  7]])

In [15]:
import numpy as np
np.random.seed(12)
arr=np.random.randint(1,21,9)
np.unique(arr,return_index=True,return_counts=True)


(array([ 3,  4,  7, 12, 13, 17, 18]),
 array([3, 4, 1, 0, 6, 7, 2], dtype=int64),
 array([1, 2, 1, 1, 1, 1, 2], dtype=int64))

In [6]:
np.random.shuffle(arr1)
arr1

array([13, 12, 18,  3, 18,  7, 17,  4,  4])

In [9]:
np.unique(arr1)


array([ 3,  4,  7, 12, 13, 17, 18])

In [8]:
np.unique(arr1).size

7

In [11]:
np.unique(arr1,return_index=true,return_counts=true)

NameError: name 'true' is not defined

In [16]:
arr=np.array([1,2,3,4,5])
arr1=np.array([5,6,7,8])
np.hstack((arr,arr1))

array([1, 2, 3, 4, 5, 5, 6, 7, 8])

In [19]:
arr3 = np.array([1,2,3,4,5])
arr4 = np.array([6,7,8,9,10])
np.vstack((arr3,arr4))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [21]:
import numpy as np
np.random.seed(33)
arr1=np.random.randint(1,20,9).reshape(3,3)
arr2=np.random.randint(21,50,9).reshape(3,3)
np.hstack((arr1,arr2))

array([[ 8,  3, 19, 24, 22, 34],
       [10,  4,  7, 33, 47, 28],
       [15, 11, 14, 33, 32, 43]])

In [22]:
np.vstack((arr1,arr2))

array([[ 8,  3, 19],
       [10,  4,  7],
       [15, 11, 14],
       [24, 22, 34],
       [33, 47, 28],
       [33, 32, 43]])

In [2]:
import numpy as np
arr =np.random.randint(1,20,10)
arr

array([13, 18,  1,  5, 14,  1, 15, 18, 13, 12])

In [3]:
arr= np.arange(10,21)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [5]:
arr= np.ones(10)*5
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [7]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr=np.arange(1,11)
arr[arr%2==0]=0
arr

array([1, 0, 3, 0, 5, 0, 7, 0, 9, 0])

In [10]:
arr=np.random.rand(9).reshape(3,3)
arr

array([[0.64145736, 0.8558511 , 0.78414382],
       [0.51896716, 0.1558866 , 0.6807246 ],
       [0.52601597, 0.64848076, 0.1122765 ]])

In [15]:
import numpy as np
arr=np.arange(1,10).reshape(3,3)
arr1=np.arange(10,19).reshape(3,3)
np.hstack(arr,arr1)

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given

In [2]:
import numpy as np
arr=np.array([10,20,30,50,60,70,80,90,100])
x=np.where(arr==80)
print(x)

(array([6], dtype=int64),)


In [3]:
x=np.where(arr==100)
print(x)

(array([8], dtype=int64),)


In [4]:
x=np.where(arr==30)
print(x)

(array([2], dtype=int64),)


In [6]:
x=np.where(arr==50)
print(x)

(array([3], dtype=int64),)


In [8]:
odd=np.where(arr%2==0)
print(odd)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64),)


In [13]:
arr1=np.array([10,25,23,45,68,40])
x=np.where(arr1==45)
print("find number=",x)
y=np.where(arr1%2==0)
print("odd index numbers=",y)
z=np.where (arr1%2 != 0)
print("even index numbers=",z)
a=np.searchsorted(arr1,15)
print("number in indexing=",a)

find number= (array([3], dtype=int64),)
odd index numbers= (array([0, 4, 5], dtype=int64),)
even index numbers= (array([1, 2, 3], dtype=int64),)
number in indexing= 1


In [26]:
import numpy as np
np.random.seed(5)
z=np.random.randint(1,10,6)
x=np.where(z==8)
print("find value after search=",x)
y=np.where(z%2==0)
print("odd indexing number=",y)
k=np.where(z%2 != 0)
print("even indexing number=",k)
l=np.searchsorted(z,4,side = 'right')
print("find indexing value given this condstion=",l)
z

find value after search= (array([], dtype=int64),)
odd indexing number= (array([0], dtype=int64),)
even indexing number= (array([1, 2, 3, 4, 5], dtype=int64),)
find indexing value given this condstion= 4


array([4, 7, 7, 1, 9, 5])

In [25]:
x=np.searchsorted(z,5)
print(x)

4


In [1]:
x=lambda a:a+15
print(x(5))

20


In [2]:
x=lambda a,b:a+b
print(x(3,4))

7


In [3]:
x=lambda a,b,c:a+b+c
print(x(5,6,7))

18


In [4]:
x=[5,10,15,20,25,30,35,40]
def my love ():
    if x < 18 :
        return False
    else:
        return True
    adults = list(filter(my love,x))
    for x in adults:
        print(x)

SyntaxError: invalid syntax (2454900489.py, line 2)

In [16]:
a=[5,12,14,16,17,19,20,22,24]
adults=filter(lambda a:a>18,a)
sequre=list(map(lambda a:a*a,adults))
print(sequre)

[361, 400, 484, 576]


In [15]:
a1=[5,7,8,9,15,18,19,20]
sex=filter(lambda a1:a1>18,a1)
sequre=list(map(lambda a1:a1*a1,a1))
print(sequre)

[25, 49, 64, 81, 225, 324, 361, 400]


In [13]:
z=[12,14,16,16,18,20,22,24]
sex=filter(lambda z:z>10,z)
sequre=list(map(lambda z:z*z,z))
print(sequre)

[144, 196, 256, 256, 324, 400, 484, 576]


In [18]:
from functools import reduce
val=[1,2,3,4,5]
add=reduce (lambda a,b:a+b,val)
print("addition=",add)

addition= 15


In [21]:
from functools import reduce

val=[5,6,7,8,9,10]
add = reduce (lambda a,b:a+b,val)
print(add)

45


In [22]:
from functools import reduce
val =[10,11,12,13,14,15,16]
add=reduce(lambda a,b:a+b,val)
print(add)

91


In [23]:
from functools import reduce
val=[12,222,2345,12343,567]
add=reduce(lambda a,b:a+b,val)
print(add)

15489


In [24]:
from functools import reduce
z=[111,222,333,444,555,6666,7789]
add=reduce(lambda a,b:a+b,z)
print(add)

16120


In [26]:
from functools import reduce
z=[1,2,3,4,5,6,7,8,9,10]
max=reduce(lambda a,b:a if a>b else b,z)
print(max)

10


In [28]:
from functools import reduce
z1=[12,34,12,465,2345,1234,3456]
add= reduce(lambda a,b: a if a>b else b,z1)
print(add)

3456


In [29]:
from functools import reduce
x=[12,23,34,56,78,90,100]
add=reduce(lambda a,b: a if a>b else b,x)
print(add)

100


In [30]:
from functools import reduce
y=[111,222,333,444,555,666,777,999,1000,10001]
add=reduce(lambda a,b: a if a>b else b,y)
print(add)

10001


In [31]:
from functools import reduce
p=[890,234,456,789,456,567]
add=reduce(lambda a,b: a if a>b else b,p)
print(add)

890
